"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages
from S3_File_Uploader import APP_VERSION

APP = ['S3_File_Uploader/main.py']
DATA_FILES = []
OPTIONS = {
    'resources': [
        'S3_File_Uploader/UI/images'
    ],
    # Any package that is not part of the standard library
    # that is used as an import, needs to be added here
    'packages': [
        'botocore',
        'boto3',
        'ffmpeg',
        'pexpect',
        'requests'
    ]
}

setup(
    name='S3 File Uploader',
    version=APP_VERSION,
    license='MIT',
    url='https://github.com/rluzuriaga/S3_File_Uploader',
    author="Rodrigo Luzuriaga",
    author_email='me@rodrigoluzuriaga.com',
    maintainer='Rodrigo Luzuriaga',
    maintainer_email='me@rodrigoluzuriaga.com',
    app=APP,
    packages=find_packages(),
    data_files=DATA_FILES,
    package_data={
        'S3_File_Uploader': ['UI/images/*.*']
    },
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        'botocore',
        'boto3',
        'ffmpeg-python',
        'pexpect',
        'requests'
    ],
    zip_safe=True,
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: MacOS X',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Operating System :: MacOS :: MacOS X',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: SQL'
    ]
)
