"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

APP = ['S3_File_Uploader/main.py']
DATA_FILES = []
OPTIONS = {
    'resources': [
        'S3_File_Uploader/UI/images'
    ],
    # Any package that is not part of the standard library
    # that is used as an import, needs to be added here
    'packages': [
        'botocore',
        'boto3',
        'ffmpeg',
        'pexpect'
    ]
}

setup(
    name='S3 File Uploader',
    app=APP,
    packages=find_packages(),
    data_files=DATA_FILES,
    package_data={
        'S3_File_Uploader': ['UI/images/*.*']
    },
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        'botocore',
        'boto3',
        'ffmpeg-python',
        'pexpect'
    ],
    zip_safe=True,
)
